### ISSUE TITLE
Merging Slax Bundles

### ISSUE THREAD

**Issue by alexandre-mbm** [fhunleth/merge-squashfs#1]
Hello! I am looking a way to merge Slax Bundles (*.sb files).

**Comment by fhunleth** [comment]
Sorry, I have no clue on that. This project was some quick toy code I wrong a long time ago, so I'm not certain it still works and I don't know anything about Slax.

**Comment by alexandre-mbm** [comment]
I did manual merging thought unsquashfs and mksquashfs.
